# 服务端口
server:
  port: 8032
# 服务名
spring:
  application:
    name: antwhale-user-dowork
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anywhale?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    jackson:
      time-zone: GMT+8
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时间
    timeout: 3000
  #上传文件大小设置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7999/xxl-job-admin  #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: testJob #xxljob配置的执行器名称，
      ip:             #执行器IP，默认为空表示自动获取IP
      port: 9999 #xxljob配置的端口号，默认为9999
      logpath: /data/xxl-job/jobhandler  #执行器运行日志文件存储磁盘路径
      logretentiondays: -1  #调度中心日志表数据保存天数，过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能
    accessToken: #调度中心通讯TOKEN [选填]：非空时启用